import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Navbar from "@/components/sections/Navbar/Navbar";
import ProfileCover from "../components/sections/ProfileCover/ProfileCover";
import Sidebar from "../components/sections/Sidebar/Sidebar";
import Footer from "../components/sections/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "John Schlesinger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen relative bg-gray-50 pb-10">
          <ProfileCover />
          <div className="container mx-auto px-4">
            <div className="flex flex-wrap px-4">
              <div className="w-full lg:w-1/3">
                <Sidebar />
              </div>
              <div className="w-full lg:w-2/3">
                <Navbar />
                {children}
              </div>
            </div>
          </div>
          <Footer />
          <div id="modal-root"></div>
        </main>
      </body>
    </html>
  );
}
